import React, {useEffect, useState} from 'react';
import {ActivityIndicator, Pressable, StatusBar, StyleSheet, Text, View} from 'react-native';
import {useSafeAreaInsets} from 'react-native-safe-area-context';
import {defaultRoute, type TopLevelRoute} from './routes';
import {persistedSession, type SessionValidator} from './session';
import {persistentRouteStore, type RouteStore} from './storage';
import {sessionCredentials} from '../shared/storage/sessionCredentials';
import {AuthScreen} from '../features/auth/AuthScreen';
import {PhotoImportScreen} from '../features/photo-import/PhotoImportScreen';
import {LearningScreen} from '../features/learning/LearningScreen';
import {EquipmentScreen} from '../features/equipment/EquipmentScreen';

const destinations: Array<{key: TopLevelRoute; label: string; kicker: string}> = [{key:'home',label:'首页',kicker:'准备好拍下一张了吗？'},{key:'learn',label:'学习',kicker:'把相机知识用到真实场景。'},{key:'portfolio',label:'作品',kicker:'记录每一次更好的尝试。'},{key:'profile',label:'我的',kicker:'你的器材、进度与设置。'}];
export type AppShellProps = {sessionValidator?: SessionValidator; routeStore?: RouteStore};
export function AppShell({sessionValidator=persistedSession,routeStore=persistentRouteStore}:AppShellProps) { const insets=useSafeAreaInsets(); const [ready,setReady]=useState(false);const [authenticated,setAuthenticated]=useState(false);const [route,setRoute]=useState<TopLevelRoute>(defaultRoute); useEffect(()=>{let active=true;Promise.all([sessionValidator.hasValidSession(),routeStore.load()]).then(([valid,saved])=>{if(active){setAuthenticated(valid);setRoute(saved);setReady(true);}});return()=>{active=false;};},[routeStore,sessionValidator]); const selectRoute=(next:TopLevelRoute)=>{setRoute(next);routeStore.save(next).catch(()=>{});};const logout=async()=>{await sessionCredentials.clear();setAuthenticated(false);};if(!ready)return <View style={styles.center}><ActivityIndicator color="#18A999" size="large"/></View>;if(!authenticated)return <AuthScreen/>;const destination=destinations.find(item=>item.key===route)!;return <View style={[styles.app,{paddingTop:insets.top,paddingBottom:insets.bottom}]}><StatusBar barStyle="dark-content"/><View style={styles.content} testID={`${route}-screen`}><Text style={styles.eyebrow}>FRAME FORWARD</Text><Text style={styles.heading}>{destination.label}</Text><Text style={styles.kicker}>{destination.kicker}</Text>{route==='home'?<PhotoImportScreen/>:route==='learn'?<LearningScreen/>:route==='profile'?<EquipmentScreen/>:<View style={styles.focusFrame}><Text style={styles.focusText}>功能即将接入</Text></View>}{route==='profile'&&<Pressable accessibilityRole="button" onPress={logout} testID="logout-button"><Text>退出登录</Text></Pressable>}</View><View accessibilityRole="tablist" style={styles.tabs}>{destinations.map(item=>{const selected=item.key===route;return <Pressable accessibilityRole="tab" accessibilityState={{selected}} key={item.key} onPress={()=>selectRoute(item.key)} style={[styles.tab,selected&&styles.selectedTab]} testID={`nav-${item.key}`}><Text style={[styles.tabLabel,selected&&styles.selectedTabLabel]}>{item.label}</Text></Pressable>;})}</View></View>;}
const styles=StyleSheet.create({app:{backgroundColor:'#F5F9F8',flex:1},center:{alignItems:'center',backgroundColor:'#F5F9F8',flex:1,justifyContent:'center'},content:{flex:1,justifyContent:'center',padding:28},eyebrow:{color:'#18A999',fontSize:12,fontWeight:'800',letterSpacing:2},heading:{color:'#102A43',fontSize:36,fontWeight:'800',marginTop:12},kicker:{color:'#52616B',fontSize:17,lineHeight:26,marginTop:8},focusFrame:{alignItems:'center',borderColor:'#18A999',borderRadius:18,borderWidth:2,justifyContent:'center',marginTop:34,minHeight:160},focusText:{color:'#102A43',fontSize:16,fontWeight:'600'},tabs:{backgroundColor:'#FFFFFF',borderTopColor:'#D9E5E2',borderTopWidth:StyleSheet.hairlineWidth,flexDirection:'row',paddingHorizontal:8,paddingTop:8},tab:{alignItems:'center',flex:1,minHeight:48,justifyContent:'center'},selectedTab:{borderTopColor:'#18A999',borderTopWidth:3},tabLabel:{color:'#718096',fontSize:13,fontWeight:'600'},selectedTabLabel:{color:'#102A43',fontWeight:'800'}});
